name: imagenet_1k
label_key: label
layer:
  _target_: torch.nn.Linear
  _args_:
    - ${backbone.feature_size}
    - 1000
loss:
  _target_: torch.nn.CrossEntropyLoss
metrics:
  - name: top1_accuracy
    metric:
      _target_: torchmetrics.classification.MulticlassAccuracy
      num_classes: 1000
      average: micro
  - name: top5_accuracy
    metric:
      _target_: torchmetrics.classification.MulticlassAccuracy
      num_classes: 1000
      top_k: 5
